# Colors (Ashen)
# Author: Daniel Fichtinger
# License: MIT
# I, dotsilva, changed it a little bit

# Default Colors
[colors.primary]
background = '#121212'
foreground = '#f5f5f5'

# Selection Colors
[colors.cursor]
cursor = '#f5f5f5'
text = '#121212'

# Normal Colors
[colors.normal]
black = '#949494'
red = '#D87C4A'
green = '#B14242'
yellow = '#E49A44'
blue = '#4A8B8B'
magenta = '#a7a7a7'
cyan = '#b4b4b4'
white = '#d5d5d5'

# Bright Colors
[colors.bright]
black = '#949494'
red = '#D87C4A'
green = '#B14242'
yellow = '#E49A44'
blue = '#4A8B8B'
magenta = '#a7a7a7'
cyan = '#b4b4b4'
white = '#d5d5d5'
